### ISSUE TITLE
Android 6.0版本闪退

### ISSUE THREAD

**Issue by lizhaode** [V2Ray-Android/Actinium#29]
先贴出logcat 
```
07-13 00:22:47.167  2354  2621 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
07-13 00:22:47.217  1341  1428 W WindowAnimator: Failed to dispatch window animation state change.
07-13 00:22:47.217  1341  1428 W WindowAnimator: android.os.DeadObjectException
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:550)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:317)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:750)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:136)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:890)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:704)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:637)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:878)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-13 00:22:47.217  1341  1428 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

复现环境：

  机器是Vivo，操作系统是6.0.1

复现步骤：
 1. 正确配置服务器信息（config.json）
 2. 软件中加载配置
 3. 点击右下角的图标，启动代理

实际结果：
 提示Actinium已停止运行

备注：
 还抓取到一次logcat

```
07-13 00:27:40.977 10251 10251 E AndroidRuntime: FATAL EXCEPTION: main
07-13 00:27:40.977 10251 10251 E AndroidRuntime: Process: com.v2ray.actinium, PID: 10251
07-13 00:27:40.977 10251 10251 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	... 1 more
07-13 00:27:40.977 10251 10251 E AndroidRuntime: Caused by: android.os.DeadObjectException
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at com.v2ray.actinium.a.a$a$a.b(Unknown Source)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at com.v2ray.actinium.ui.MainActivity$c.onServiceDisconnected(Unknown Source)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1238)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1252)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5628)
07-13 00:27:40.977 10251 10251 E AndroidRuntime: 	... 3 more
07-13 00:27:40.977  1341  1363 I ActivityManager: handleApplicationCrash callcom.v2ray.actinium
```

**Comment by xiaokangwang** [comment]
@liberal-boy  应该在出现异常的时候对异常进行捕获并处理。

**Comment by xiaokangwang** [comment]
我自己在https://appetize.io/的虚拟机上重现了这个问题，但是在自己的手机上还是能用。
[2017-07-16 10-54-52 debug log.txt](https://github.com/V2Ray-Android/Actinium/files/1150807/2017-07-16.10-54-52.debug.log.txt)
[2017-07-16 10-49-29 debug log.txt](https://github.com/V2Ray-Android/Actinium/files/1150808/2017-07-16.10-49-29.debug.log.txt)
![2017-07-16 10-49-24 screenshot](https://user-images.githubusercontent.com/1883569/28244174-649195e8-6a15-11e7-8437-b653291b7342.jpg)
![2017-07-16 10-47-32 screenshot](https://user-images.githubusercontent.com/1883569/28244177-65ec3a4c-6a15-11e7-97e8-ec7aaec58493.jpg)
![2017-07-16 10-59-50 screenshot](https://user-images.githubusercontent.com/1883569/28244195-ef0bd2d8-6a15-11e7-95ef-1c51f0ada6c0.jpg)
感觉和处理器的架构有关系（无证据）。

**Comment by xiaokangwang** [comment]
在 https://github.com/xiaokangwang/AndroidLibV2ray/commit/9c107f17ffce0af62d207a90fc67c9380d8fc9ed  进行了修复的尝试，需要在使用了这个版本的Ac之后才能确定是否解决了问题。

**Comment by lizhaode** [comment]
@xiaokangwang 感觉应该和处理器无关吧，毕竟是骁龙的，理论上兼容性应该是最好的

**Comment by liberal-boy** [comment]
修复于 6e81426
